# Generated by Django 5.2.13 on 2026-05-04 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('predicted_subtype', models.CharField(blank=True, max_length=20, null=True)),
                ('luad_confidence', models.FloatField(blank=True, null=True)),
                ('lusc_confidence', models.FloatField(blank=True, null=True)),
                ('total_genes_analyzed', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('current_step_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=50)),
                ('drug_name', models.CharField(max_length=100)),
                ('chembl_id', models.CharField(blank=True, max_length=50)),
                ('mechanism', models.TextField(blank=True)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('max_phase', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.patientanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=50)),
                ('report_text', models.TextField()),
                ('sections', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.patientanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('top_genes', models.JSONField()),
                ('top_drugs', models.JSONField()),
                ('clinical_recommendations', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.patientanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='XAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_index', models.IntegerField()),
                ('gene_symbol', models.CharField(max_length=50)),
                ('shap_value', models.FloatField()),
                ('lime_weight', models.FloatField()),
                ('shap_direction', models.CharField(max_length=10)),
                ('lime_direction', models.CharField(max_length=10)),
                ('high_confidence', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.patientanalysis')),
            ],
        ),
    ]
